services:
  django_website:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media/
    ports:
      - "8000:8000"
    networks:
    - app-network
  
  streamlit_website:
    image: pravesh1800/portfolio:latest
    ports:
      - "8501:8501"
    networks:
    - app-network
      
  nginx:
    image: nginx
    volumes:
      - ./media:/media/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./staticfiles:/usr/share/nginx/html/staticfiles  # Assuming your static files are in ./staticfiles
      - ./logs:/var/log/nginx
    environment: 
      - SERVER_ADDR=django_website:8000
      - SERVER_ADDR=streamlit_website:8501
    #command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "90:90"
    depends_on:
      - django_website
      - streamlit_website

networks:
  app-network:
  

  