# Generated by Django 5.0.6 on 2024-05-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageUpload',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
